# Generated by Django 6.0.4 on 2026-04-18 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0002_geofencearea_locationlog'),
        ('orders', '0004_order_drop_lat_order_drop_lng_order_pickup_lat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notification_type', models.CharField(choices=[('order_created', 'Order Created'), ('order_assigned', 'Order Assigned'), ('order_completed', 'Order Completed'), ('order_cancelled', 'Order Cancelled'), ('driver_nearby', 'Driver Nearby'), ('chat_message', 'Chat Message'), ('system_alert', 'System Alert'), ('geofence_alert', 'Geofence Alert'), ('location_suspicious', 'Suspicious Location')], max_length=50)),
                ('title_template', models.CharField(help_text='Template for notification title', max_length=200)),
                ('message_template', models.TextField(help_text='Template for notification message')),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Urgent'), (5, 'Critical')], default=2)),
                ('variables_schema', models.JSONField(default=dict, help_text='Schema for template variables')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='FCM device token', max_length=255, unique=True)),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=20)),
                ('device_id', models.CharField(blank=True, help_text='Unique device identifier', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('order_created', 'Order Created'), ('order_assigned', 'Order Assigned'), ('order_completed', 'Order Completed'), ('order_cancelled', 'Order Cancelled'), ('driver_nearby', 'Driver Nearby'), ('chat_message', 'Chat Message'), ('system_alert', 'System Alert'), ('geofence_alert', 'Geofence Alert'), ('location_suspicious', 'Suspicious Location')], max_length=50)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Urgent'), (5, 'Critical')], default=2)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_error', models.TextField(blank=True)),
                ('is_spam_blocked', models.BooleanField(default=False)),
                ('spam_reason', models.TextField(blank=True)),
                ('data', models.JSONField(default=dict, help_text='Additional data for the notification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch.branch')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['notification_type', '-created_at'], name='notificatio_notific_d8746a_idx'), models.Index(fields=['is_read', '-created_at'], name='notificatio_is_read_1cb71a_idx'), models.Index(fields=['priority', '-created_at'], name='notificatio_priorit_3fc670_idx')],
            },
        ),
    ]
