# Generated by Django 6.0.4 on 2026-04-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_type',
            field=models.CharField(choices=[('ojek', 'Ojek'), ('delivery', 'Delivery'), ('kurir', 'Kurir'), ('belanja', 'Belanja'), ('mobil', 'Mobil'), ('travel', 'Travel'), ('gift', 'Gift')], default='ojek', max_length=20),
        ),
    ]
