# Generated by Django 6.0.4 on 2026-04-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='drop_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='drop_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
