# Generated by Django 6.0.4 on 2026-04-16 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('5_days', '5 Hari'), ('15_days', '15 Hari'), ('30_days', '30 Hari')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_orders', models.IntegerField(default=0)),
                ('total_tarif', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deduction_percentage', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('settlement_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branch')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end', '-created_at'],
                'unique_together': {('driver', 'branch', 'period', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='SettlementDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=50)),
                ('tarif', models.DecimalField(decimal_places=2, max_digits=12)),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('settlement_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pickup_location', models.TextField()),
                ('drop_location', models.TextField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_items', to='settlement.driversettlement')),
            ],
            options={
                'ordering': ['order__created_at'],
            },
        ),
    ]
