# Generated by Django 6.0.4 on 2026-04-18 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeofenceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama area (contoh: Pusat Kota, Terminal, dll)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Deskripsi area')),
                ('center_latitude', models.FloatField(help_text='Latitude pusat area')),
                ('center_longitude', models.FloatField(help_text='Longitude pusat area')),
                ('radius_meters', models.PositiveIntegerField(default=1000, help_text='Radius area dalam meter')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Prioritas area (lebih tinggi = lebih prioritas)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_areas', to='branch.branch')),
            ],
            options={
                'ordering': ['-priority', 'name'],
                'unique_together': {('branch', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', models.FloatField(blank=True, help_text='GPS accuracy dalam meter', null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, help_text='Kecepatan dalam m/s', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Heading/direction dalam degrees', null=True)),
                ('gps_timestamp', models.DateTimeField(blank=True, help_text='Timestamp dari GPS device', null=True)),
                ('is_mock_location', models.BooleanField(default=False, help_text='Apakah lokasi ini mock/fake')),
                ('provider', models.CharField(blank=True, help_text='GPS provider (gps, network, fused)', max_length=50, null=True)),
                ('is_valid', models.BooleanField(default=True, help_text='Apakah lokasi valid berdasarkan geofencing')),
                ('is_suspicious', models.BooleanField(default=False)),
                ('suspicion_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch.branch')),
                ('geofence_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch.geofencearea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='branch_loca_user_id_67c541_idx'), models.Index(fields=['is_valid', 'is_suspicious'], name='branch_loca_is_vali_349bdd_idx'), models.Index(fields=['latitude', 'longitude'], name='branch_loca_latitud_c1e823_idx')],
            },
        ),
    ]
